title: Andrés Franco
email: hello@andresfran.co
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://andresfran.co" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: andfkco
github_username:  andfk

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      author: Andrés
      layout: "post"

# Build settings
markdown:       kramdown
paginate:       5
paginate_path:  "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
